CREATE TABLE training_data (
	id INT NOT NULL AUTO_INCREMENT,
	Prefix VARCHAR(255) NOT NULL DEFAULT '',
	Suffix VARCHAR(255) NOT NULL DEFAULT '',
	Full_Name VARCHAR(255) NOT NULL DEFAULT '',
	First_Name VARCHAR(255) NOT NULL DEFAULT '',
	Middle_Name VARCHAR(255) NOT NULL DEFAULT '',
	Last_Name VARCHAR(255) NOT NULL DEFAULT '',
	PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;